{
 "title": "10-03-Dash Nelipin",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Free space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\r\nnode_filesystem_free_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\", mountpoint=\"/\"}",
     "legendFormat": "on /"
    }
   ]
  },
  {
   "title": "Load average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}",
     "legendFormat": "LA 1 min"
    },
    {
     "expr": "node_load5{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}",
     "legendFormat": "LA 5 min"
    },
    {
     "expr": "node_load15{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}",
     "legendFormat": "LA 15 min"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time (node_memory_MemFree_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}[20s])",
     "legendFormat": "MemFree"
    },
    {
     "expr": "avg_over_time (node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}[20s])",
     "legendFormat": "MemAvail"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (rate(node_cpu_seconds_total{instance=\"nodeexporter:9100\", job=\"nodeexporter\", mode=\"idle\"}[10s]) * 100)\r",
     "legendFormat": "100% - Idle"
    }
   ]
  }
 ]
}